# Generated by Django 5.2.11 on 2026-02-27 07:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('fingerprint', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='unresolved', max_length=20)),
                ('first_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['status', '-last_seen'], name='idx_status_last_seen')],
            },
        ),
    ]
